export const CONTACTS = 'Contacts'
export const EDIT_PROFILE = 'Edit Profile'
export const HOME = 'Home'
export const LOGIN = 'Login'
export const PROFILE = 'Profile'
export const SIGNUP = 'Register'
export const SETTINGS = 'Settings'
